cc_library(
    name = "debug",
    srcs = ["debug.cpp"],
    hdrs = ["debug.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//value:value",
        "//instruction:chunk",
    ],
)
