cc_library(
    name = "vm",
    srcs = ["vm.cpp"],
    hdrs = ["vm.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//instruction:chunk",
        "//value:value",
        "//debug:debug",
    ],
)
